name: 'Test'
description: 'Just a test'
inputs:
  name:
    description: 'Your name'
    required: true
    default: 'No name provided'
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.name }}
      shell: bash